echo "复制文件..."  
copy /y ..\..\SFL\CDOAnalyzer.DataAccess\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\CDOAnalyzer.Services\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Accumulator\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Calendar\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CashFlow\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Accounts\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Base\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Collateral\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.CreditEnhancement\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Data\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Fees\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.InterestRateHedge\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Notes\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Tests\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Util\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDO.Waterfall\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDOAnalyser\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDOAnalyser.CalcService\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDOAnalyser.MasterData\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDOAnalyser.WinForms\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CDODefaultGenerator\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.CdoScope.Util\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.ChineseAbs\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.ChineseAbs.Assets\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Curves\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Curves.Spline\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Data\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.DataBase\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Database.Sql\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Enumerations\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.EventRate\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Expressions\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Factories.UI\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Factory.Base\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.FixedIncomeCalculator\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.FlexGrid\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.ForwardRates\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.InterestRates\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Interfaces\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.MathLib\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Mathlib.NMath\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.NET\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Observations\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Parsers\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.ResetRates\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Schedules\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Schedules.Data\bin\Debug  .\bin\Debug\SFL 
copy /y ..\..\SFL\SFL.Types\bin\Debug  .\bin\Debug\SFL 

echo 复制成功